version: '3,9'
services:
  mysql8:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring



  postgres14:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: sas
      postgres_db: mscv_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    networks:
      - spring

  msvc-usuarios:
    image: usuarios
    ports:
      - "8001:8001"
    env_file: ./msvc-usuarios/.env
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always


  mcsv-cursos:
    image: cursos
    ports:
      - "8002:8002"
    env_file: ./mcsv-cursos/.env
    networks:
      - spring
    depends_on:
      - postgres14
    restart: always



  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "elias@elias.com"
      PGADMIN_DEFAULT_PASSWORD: "elias"
    ports:
      - "80:80"
    depends_on:
      - db-cursos

volumes:
  data-mysql:
  data-postgres:

networks:
  spring: