version: '3,9'
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: msvc_usuarios

    restart: always
    networks:
      - spring


  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mscv_cursos
      POSTGRES_USER: elias
      POSTGRES_PASSWORD: elias
    volumes:
      - data-postgres:/var/lib/postgresql/data
    networks:
      - spring
    expose:
      - 5432

  msvc-usuarios:
    container_name: msvc-usuarios
    image: eliasroy/usuarios
    #build:
    #  context: ./
     # dockerfile: ./msvc-usuarios/Dockerfile
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      BD_HOST: mysql8:3306
      BS_DATABASE: msvc_usuarios
      DB_USERNAME: root
      DB_PASSWORD: sasa
      CURSOS_URL: mcsv-cursos:8002
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always




  mcsv-cursos:
    container_name: mcsv-cursos
    image: eliasroy/cursos
      #build:
      #context: ./
    #dockerfile: ./mcsv-cursos/Dockerfile
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      BD_HOST: postgres14:5432
      BD_DATABASE: mscv_cursos
      DB_USERNAME: elias
      DB_PASSWORD: elias
      USUARIOS_URL: msvc-usuarios:8001
    networks:
      - spring

    restart: always



  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "elias@elias.com"
      PGADMIN_DEFAULT_PASSWORD: "elias"
    ports:
      - "80:80"
    depends_on:
      - postgres14

volumes:
  data-mysql:
    name: "data-mysql"
  data-postgres:
    name: "data-postgres"

networks:
  spring: