version: '3'
services:
  db-usuario:
    container_name: db-usuario
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_orders
      MYSQ_USER: uncledave
      MYSQ_PASSWORD: Test123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306